name: cam
dependencies:
  - python=3.7
  - pip=20.0
  - Keras-Applications=1.0.8
  - Keras-Preprocessing=1.1.0
  - matplotlib=3.1.3
  - numpy=1.18.1
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - tensorboard=2.1.0
  - tensorflow=2.1.0
  - tensorflow-estimator=2.1.0
  - pip:
      - mido==1.2.9
      - librosa==0.7.2
      - tensorflow-metadata==0.21.1
      - tensorflow-probability==0.9.0
      - tensorboard-plugin-wit==1.6.0.post2
      - tensorflow-datasets==2.1.0
      - pyyaml==3.5.1
