hparams:
  name: 'gan'
  plot: False
  epochs: 100
  steps: 1000
  sample_rate: 16000
  batch_size: 32
  buffer_size: 1000
  latent_size: 100
  cond_vector_size: 88
  generator_scale: 128
  gen_lr: 0.0001
  disc_lr: 0.0004
  log_amin: 0.00001
  num_examples: 16
  save_dir: './'
  save_images: False
