hparams:
  name: new_gan
  dataset: magphase
  instrument:
    family: 'guitar'
  pitches: 61
  sample_rate: 16000
  frame_length: 2048
  frame_step: 512
  n_mels: 1024
  latent_dim: 128
  n_blocks: 6
  lr: 0.00002
  buffer_size: 100
  save_dir: '.'
  finished_epochs: 4
  finished_batch_size: 4
  batch_sizes:
    - 64
    - 32
    - 32
    - 16
    - 8
    - 4
  epochs:
    - 4
    - 6
    - 6
    - 8
    - 10
    - 1
