hparams:
  name: 'sinenet'
  instrument:
    family: 'string'
  epochs: 10000
  steps: 0
  sample_rate: 8000
  samples: 8000
  pitches: 64
  history: 20
  params: 3
  batch_size: 8
  buffer_size: 100
  latent_size: 100
  scale: 128
  lr: 0.01
  num_examples: 16
  save_dir: './'
  ckpt_every_step: 100
