hparams:
  name: 'sinenet'
  instrument:
    family: 'string'
  epochs: 10000
  steps: 0
  sample_rate: 16000
  samples: 16000
  pitches: 128
  history: 512
  params: 3
  batch_size: 32
  buffer_size: 100
  latent_size: 100
  scale: 128
  lr: 0.001
  num_examples: 16
  save_dir: './'
  ckpt_every_step: 1000
