hparams:
  name: 'sinenet'
  instrument:
    family: 'keyboard'
  epochs: 100
  steps: 1000
  sample_rate: 16000
  samples: 64000
  channels: 16
  batch_size: 32
  buffer_size: 100
  latent_size: 100
  scale: 128
  lr: 0.001
  num_examples: 16
  save_dir: './'
