hparams:
  name: 'transformer'
  epochs: 20
  steps: 0
  num_layers:
    min: 1
    max: 6
    step: 1
  d_model:
    min: 32
    max: 512
    step: 32
  dff:
    min: 32
    max: 512
    step: 32
  num_heads:
    min: 1
    max: 4
    step: 1
  frame_size: 256
  batch_size: 32
  buffer_size: 1000
  dropout_rate:
    min: 0.05
    max: 0.4
    step: 0.05
  beta_1: 0.9
  beta_2: 0.98
  epsilon: 0.000000001
  save_dir: './'
