hparams:
  name: 'vae'
  epochs: 10
  steps: 10
  sample_rate: 16000
  window_samples: 8000
  batch_size: 64
  buffer_size: 1000
  latent_size: 100
  model_scale: 32
  lr: 0.001
  log_amin: 0.00001
  num_examples: 1
  save_dir: '.'
