hparams:
  name: 'vae'
  epochs: 100
  steps: 0
  sample_rate: 16000
  window_samples: 4000
  batch_size: 16
  buffer_size: 5000
  latent_size: 128
  model_scale: 16
  lr: 0.001
  log_amin: 0.000001
  num_examples: 1
  save_dir: '.'
  ckpt_every_step: 2000
